replicaCount: 1

image:
  repository: docker.io/yourusername/galemind-server
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: galemind-server.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
    nvidia.com/gpu: 1
  requests:
    cpu: 500m
    memory: 1Gi
    nvidia.com/gpu: 1

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

# HashiCorp Vault configuration
vault:
  enabled: true
  role: "galemind-server"
  secretPath: "secret/galemind-server"
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "galemind-server"

# MLflow configuration
mlflow:
  enabled: true
  replicaCount: 1

  image:
    repository: python
    tag: "3.9-slim"
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 5000

  # MLflow backend store (file-based by default, can be database)
  backendStore: "file:///mlflow/mlruns"

  # MLflow artifact store
  artifactStore: "/mlflow/artifacts"

  # Database configuration (optional)
  database:
    enabled: false
    uri: ""  # e.g., "postgresql://user:password@postgres:5432/mlflow"

  # Persistence for MLflow data
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: ""

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}

  env:
    - name: MLFLOW_HOST
      value: "0.0.0.0"
    - name: MLFLOW_PORT
      value: "5000"

env:
  - name: RUST_LOG
    value: "info"